# Generated by Django 2.1.2 on 2018-10-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='docfile',
        ),
        migrations.AddField(
            model_name='document',
            name='_data',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='_user',
            field=models.CharField(default=1234, max_length=150),
            preserve_default=False,
        ),
    ]
