# Generated by Django 2.1.2 on 2018-10-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlobField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_data1', models.BinaryField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
