# Generated by Django 2.1.2 on 2018-10-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20181024_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='_file_path',
            field=models.CharField(default='Older', max_length=1000),
            preserve_default=False,
        ),
    ]
