# Generated by Django 2.1.2 on 2018-10-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20181023_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foo',
            name='_data',
            field=models.BinaryField(blank=True),
        ),
    ]
