# Generated by Django 2.1.2 on 2018-10-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20181023_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='foo',
            name='_user',
            field=models.CharField(default=123, max_length=150),
            preserve_default=False,
        ),
    ]
