# Generated by Django 2.1.2 on 2018-10-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_foo__user'),
    ]

    operations = [
        migrations.AddField(
            model_name='foo',
            name='_path',
            field=models.FileField(default=123, upload_to=''),
            preserve_default=False,
        ),
    ]
